### ISSUE TITLE
Mexico 2024 Legislative election maps

### ISSUE THREAD

**Issue by hanrodz** [yapms/YAPms#610]
Talked to @Flizzyclone about adding these maps so I started extracting the federal electoral districts from a National Electoral Institute (INE) map.

A few questions:
- There are 500 legislators in the Chamber of Deputies: 300 by direct vote (i.e. one per district) and 200 by proportional representation (40 per [circunscription](https://en.wikipedia.org/wiki/Electoral_regions_of_Mexico)). Given that the latter 200 depend on total vote percentages, I'm considering making the map such that it only accounts for the 300 directly elected deputies. How should this be handled?
- Same question with the Senate, 32 out of the 128 senators are PR (no circunscriptions, just total vote percentages).
- The remaining 96 senators are split into 2 groups: 64 relative majority and 32 first minority. There are 32 federal entities, whoever comes first place gets 2 seats (relative majority) and second place gets 1 (first minority), therefore, there's always 2 different parties for each state (and sometimes the 2 relative majority may come from different parties through coalitions, so 3 different parties). I thought this could be represented by having a map of the states and two dots inside each state (or off the coast if the entity is too small). Would this approach be right or would you suggest something else?

**Comment by Fish1** [comment]
For maps that have both proportional representation and direct representation, you can look at the Korean map. There is big button off to the side that represents the proportional representation. This is a way you could include all 500 legislators.
https://yapms.com/app/kor/national_assembly/2020001/blank

As for the senate... correct me if I'm wrong, but it sounds like you want the actual federal entity borders to represent the party that gets second place, and the two dots to represent the party(s) that got first place? It feels weird to have dots represent the first-place winner(s), because the dots make it feel secondary.

Personally, I'd say, give the borders of the federal entity two points, and let the user split edit it. And have a dot represent the party that got 2nd place.

Or if you want to keep it even simpler, just give each federal entity 3 value, and set the maps default mode to split edit, to encourage people to use the split editor.

**Comment by Flizzyclone** [comment]
Another way you could do the PR representatives is the way we do it in the German map, since I know there are technically PR districts.

https://yapms.com/app/deu/bundestag/2021269/blank

I agree with Fish on the Senate questions. value=2 for the geographic representation + a circle is the way to go. If two different parties win relative majority and the user splits as a result, that will show up striped:

![Screenshot_20240319-091715.png](https://github.com/yapms/yapms/assets/42476312/c877aa6d-8b28-4a37-8641-5bb8f9e8d594)

**Comment by Fish1** [comment]
Yes, if the PR is per district than the German map example makes more sense.

The Korean one would be better for nationwide popular vote.

**Comment by hanrodz** [comment]
Perfect, I'll go with state[value=2] + dot[value=1], and for PR seats I'll follow the German model for the Chamber of Deputies (5 circunscription lists) and the Korean model for the Senate (single list). Thanks.

As a side note, I was not aware votes could be split. Perhaps instead of "Mode" being an L2 menu, modes could be displayed as buttons at the bottom like parties are displayed at the top.

**Comment by Flizzyclone** [comment]
> As a side note, I was not aware votes could be split. Perhaps instead of "Mode" being an L2 menu, modes could be displayed as buttons at the bottom like parties are displayed at the top.

This is a good suggestion, I have noticed users not knowing about the different modes as well. Something to prototype I think
