### ISSUE TITLE
Navbar needs to scroll on overflow

### ISSUE THREAD

**Issue by Fish1** [yapms/YAPms#72]
Especially for mobile devices, the navigation bar needs to be scroll-able by the user.

**Comment by Flizzyclone** [comment]
This comes with an issue. When overflow-x is set to scroll for the navbar, so is overflow-y, creating this behavior for dropdowns where you have to scroll in order to see the dropdown options:
![yapmsBrokenDropdowns](https://user-images.githubusercontent.com/42476312/209482003-73b83b45-8dc4-487b-a7dd-f812282ffd63.gif)

We can fix the vertical scrolling with overflow-y-clip while keeping horizontal scrolling, but it makes the dropdowns unusable as the actual options are unable to be selected.

The best solution I have for this currently is to make all dropdowns into modals like yapms1.

**Comment by Fish1** [comment]
Yeah, I think all modals on mobile would be good. Drop downs aren't too friendly for mobile.
